from pathlib import Path


def universal_tag_prefix() -> str:
    """
    Returns a prefix for tags generated by the system.

    Returns
    -------
    str
        The prefix.
    """
    return "wigwam"


def install_prefix() -> str:
    """
    Returns the build system's install prefix.

    Returns
    -------
    str
        The install prefix.
    """
    return "/app"


def build_prefix() -> str:
    """
    Returns the build system's build prefix.

    Returns
    -------
    str
        The build prefix.
    """
    return "/tmp/build"


def default_workflowdata_path() -> Path:
    """The default workflowdata.json path"""
    return Path("workflowdata.json")


def default_workflowtest_path() -> Path:
    """The default workflowtests.json path"""
    return Path("workflowtests.json")
